// Angular/TodoList/src/app/layouts/layout/layout.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { Header } from '../../components/header/header';
import { Notification } from '../../components/notification/notification';
import { Footer } from '../../components/footer/footer';

@Component({
  selector: 'app-layout',
  imports: [RouterOutlet, Header, Footer],
  templateUrl: './layout.html',
  styleUrl: './layout.css',
})
export class Layout {}

// React/techNews/src/pages/layout/layout.jsx
import Header from "../../components/header/header";
import Footer from "../../components/footer/footer";
import { Outlet } from "react-router";
import "../layout/layout.css";

const Layout = () => {

  return (
    <div className="layout-wrapper">
      <Header></Header>
      <Outlet></Outlet>
      <Footer></Footer>
    </div>
  );
};

export default Layout;
